#!/usr/bin/env bash

git_ci() {
  export WKDIR="$(pwd)"
  source_env "${HOME}/.env/${1}.envrc"
}

workspace() {
  export WKSP_HOME="$(pwd)"
  export WORKSPACE="$(basename "$WKSP_HOME")"
  export WKSP_CONF="${WKSP_HOME}/config"
  export AWS_CONFIG_FILE="${WKSP_CONF}/aws"
  export KUBECONFIG="${WKSP_CONF}/kubeconfig.yaml"
  export CLOUDSDK_CONFIG="${WKSP_CONF}/gcloud"
  export DUPLO_CONFIG="${WKSP_CONF}/duplo.yaml"
}
